from pathlib import Path
import os

POM_NAMESPACE = 'http://maven.apache.org/POM/4.0.0'

MUTATION_TIMEOUT = 20 * 60  # 20m

# the base dir of the project
BASE_DIR = Path(__file__).absolute().parent.parent

RUBY = '/Users/grano/.rvm/rubies/ruby-2.2.1/bin'

SCRIPT_READABILITY = BASE_DIR / 'metrics/readability/compute_readability.rb'

LOGS_DIR = BASE_DIR / 'logs'

# the directory that contains the data
DATA_DIR = BASE_DIR / 'data'

# directory containing the data frames to answer RQ1 (generated by the R script)
RQ1_DIR = DATA_DIR / 'rq1'

# the directory that contains the plots
PLOT_DIR = BASE_DIR / 'plots'

# the installation directory of Defect4j in the system
DEFECT4J = '/Users/grano/Documents/PhD/defects4j/framework/bin'

METRICS_DIR = BASE_DIR / 'metrics'

# test smell jar
TEST_SMELL_JAR = BASE_DIR / 'metrics/test-smells/test-smells.jar'

# code smell jar
CODE_SMELL_JAR = BASE_DIR / 'metrics/code-quality/code-smells.jar'

# ck metrics jar
CK_METRICS_JAR = BASE_DIR / 'metrics/code-quality/code-quality.jar'

# readability path
READABILITY_PATH = BASE_DIR / 'metrics/readability'

# the path that contains the projects
PROJECTS_DIR = BASE_DIR / 'projects'

# the path of the Python package for the mutation
MUTATION_PACKAGE = BASE_DIR / 'effectiveness/mutation'

RESULTS_DIR = BASE_DIR / 'results'

# the path that contains the mutation results
MUTATION_RESULTS_DIR = RESULTS_DIR / 'mutation'

DEFAULT_OPERATORS = ['CONDITIONALS_BOUNDARY',
                     'NEGATE_CONDITIONALS',
                     'MATH',
                     'INCREMENTS',
                     'INVERT_NEGS',
                     'RETURN_VALS',
                     'VOID_METHOD_CALLS']
ADDITIONAL_OPERATORS = ['CONSTRUCTOR_CALLS',
                        'INLINE_CONSTS',
                        'NON_VOID_METHOD_CALLS',
                        'REMOVE_CONDITIONALS',
                        'EXPERIMENTAL_MEMBER_VARIABLE',
                        'EXPERIMENTAL_SWITCH']

ALL_OPERATORS = ["ALL", "DEFAULT"] + DEFAULT_OPERATORS + ADDITIONAL_OPERATORS
